Repository cross-seed/cross-seed.org, pull requests merged in 2024-05, with the labels that each got.

#27 Fix a bug in docker-compose.yml (in getting-started.md)
  docs/basics/getting-started.md
Labels: bug, documentation

#26 overhaul(everything): complete overhaul and update to docs and v6
  docs/basics/daemon.md
  docs/basics/faq-troubleshooting.md
  docs/basics/getting-started.md
  docs/basics/options.md
  docs/reference/api.md
  docs/reference/architecture.md
  docs/reference/utils.md
  docs/tutorials/data-based-matching.md
  docs/tutorials/unraid.md
  docs/v6-migration.md
  docusaurus.config.js
  src/css/custom.css
  static/img/dark-hero-bg.png
  static/img/dark-hero-bw-bg.png
  static/img/light-hero-bg.png
Labels: documentation

#31 update(v6-migration): update qbit flatLinking recommendations
  docs/basics/options.md
  docs/v6-migration.md
Labels: documentation, enhancement

#29 update(v6-migration): add arr integration info
  docs/basics/faq-troubleshooting.md
  docs/basics/options.md
  docs/tutorials/data-based-matching.md
  docs/v6-migration.md
Labels: documentation, enhancement

#32 fix(options/linkDir): change placement of faq
  docs/basics/options.md
  docs/v6-migration.md
Labels: bug
