Repository cross-seed/cross-seed.org, pull requests merged in 2025-02, with the labels that each got.

#78 feat(cmd): add cmd to update torrent_cache trackers
  docs/reference/utils.md
Labels: enhancement

#81 update(matchMode): use "strict" and "flexible" instead of "safe" and "risky"
  docs/basics/faq-troubleshooting.md
  docs/basics/options.md
  docs/reference/tracker-impact.md
  docs/tutorials/data-based-matching.md
  docs/tutorials/linking.md
  docs/tutorials/partial-matching.md
  docs/v6-migration.md
Labels: documentation

#79 feat(api): add docs for /api/job
  docs/basics/faq-troubleshooting.md
  docs/reference/api.md
Labels: enhancement

#65 add(daemon/winodws): instructions for managing the daemon on Windows
  docs/basics/managing-the-daemon.mdx
Labels: documentation, good first issue

#82 options(ouputDir): nullish
  docs/basics/_docker-compose.md
  docs/basics/faq-troubleshooting.md
  docs/basics/getting-started.mdx
  docs/basics/options.md
  docs/tutorials/injection.md
  docs/tutorials/unraid.md
Labels: documentation
